### PR TITLE
Fix windows rename detection

### LINKED ISSUE #91: Fix flaky detection of file renames on Windows
```text
10:34:09.143  INFO    >>> Running 'can detect file moved in'
10:34:09.145  INFO    > Creating C:\tcagent1\temp\buildTmp\junit1844794372588176522\junit588397345475646162\source-outside.txt
10:34:09.145  INFO    < Created C:\tcagent1\temp\buildTmp\junit1844794372588176522\junit588397345475646162\source-outside.txt
10:34:09.196  INFO    Server thread 11404 with handle 000000000000048C running
10:34:09.196  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in'
10:34:09.197  INFO    > Expecting CREATED C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in\target-inside.txt
10:34:09.197  FINE    Change detected: 0x1 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in\target-inside.txt'
10:34:09.198  INFO    > Received  CREATED C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in\target-inside.txt
10:34:09.198  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in'
10:34:09.198  FINE    Change detected: 0x3 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in\target-inside.txt'
10:34:09.199  INFO    > Received  MODIFIED C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in\target-inside.txt
10:34:09.199  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in'
10:34:09.201  FINE    Requesting termination of server thread 000000000000048C
10:34:09.201  INFO    Finished watching 'C:\tcagent1\temp\buildTmp\junit1844794372588176522\can detect file moved in'
10:34:09.201  INFO    Server thread 11404 finishing
10:34:09.202  INFO    Termination of server thread 000000000000048C finished normally
10:34:09.202  INFO    <<< Finished 'can detect file moved in'
```

and:

```text
10:34:08.906  INFO    >>> Running 'can detect file renamed'
10:34:08.907  INFO    > Creating C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\source.txt
10:34:08.907  INFO    < Created C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\source.txt
10:34:08.959  INFO    Server thread 7796 with handle 000000000000048C running
10:34:08.960  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed'
10:34:08.961  INFO    > Expecting REMOVED C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\source.txt
10:34:08.967  FINE    Change detected: 0x4 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\source.txt'
10:34:08.967  INFO    > Received  REMOVED C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\source.txt
10:34:08.968  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed'
10:34:08.968  FINE    Change detected: 0x3 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\target.txt'
10:34:08.969  INFO    > Received  MODIFIED C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed\target.txt
10:34:08.975  FINE    Watching directory 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed'
10:34:09.077  FINE    Requesting termination of server thread 000000000000048C
10:34:09.080  INFO    Finished watching 'C:\tcagent1\temp\buildTmp\junit6545636757211262256\can detect file renamed'
10:34:09.081  INFO    Server thread 7796 finishing
10:34:09.082  INFO    Termination of server thread 000000000000048C finished normally
10:34:09.082  INFO    <<< Finished 'can detect file renamed'
```

### PR DESCRIPTION
**Pull request by lptr**
Fixes #91 
🤦‍♂

### CODE REVIEW

File: src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy [hunk 1]
```diff
@@ -174,35 +174,30 @@ abstract class AbstractFileEventsTest extends Specification {
...
         createNewFile(sourceFile)
-        // TODO Why doesn't Windows report the creation of the target file?
-        def expectedEvents = Platform.current().windows
-            ? [removed(sourceFile)]
-            : [removed(sourceFile), created(targetFile)]
         startWatcher(rootDir)
 
         when:
-        def expectedChanges = expectEvents expectedEvents
+        // TODO Why doesn't Windows report the creation of the target file?
```
Comment (wolfs) [inline src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy]: This comment should be removed, right?

Comment (lptr) [reply src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy]: Well spotted, removed.
